---
- name: Install Redis
  apt:
    name: "{{ redis_apt_package }}"
    state: present
    update_cache: yes

- name: Enable service Redis, and not touch the state
  service:
    name: "{{ redis_service_name }}"
    enabled: yes
